# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1401, 760)
        MainWindow.setMinimumSize(QtCore.QSize(1401, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1401, 843))
        MainWindow.setStyleSheet("background-color: rgb(120, 180, 90);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 1381, 141))
        self.groupBox.setStyleSheet("background-color: rgb(100, 160, 90);")
        self.groupBox.setObjectName("groupBox")
        self.execute_button = QtWidgets.QPushButton(parent=self.groupBox)
        self.execute_button.setGeometry(QtCore.QRect(10, 55, 1361, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.execute_button.setFont(font)
        self.execute_button.setStyleSheet("background-color: rgb(140, 200, 90);")
        self.execute_button.setObjectName("execute_button")
        self.layoutWidget = QtWidgets.QWidget(parent=self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 1361, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.choose_input_button = QtWidgets.QToolButton(parent=self.layoutWidget)
        self.choose_input_button.setStyleSheet("background-color: rgb(140, 200, 90);")
        self.choose_input_button.setObjectName("choose_input_button")
        self.gridLayout.addWidget(self.choose_input_button, 0, 2, 1, 1)
        self.input_filename = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.input_filename.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.input_filename.setObjectName("input_filename")
        self.gridLayout.addWidget(self.input_filename, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 160, 1381, 571))
        self.groupBox_3.setStyleSheet("background-color: rgb(100, 160, 90);")
        self.groupBox_3.setObjectName("groupBox_3")
        self.output_text = QtWidgets.QTextBrowser(parent=self.groupBox_3)
        self.output_text.setGeometry(QtCore.QRect(10, 20, 1361, 541))
        self.output_text.setMinimumSize(QtCore.QSize(1361, 0))
        self.output_text.setMaximumSize(QtCore.QSize(1361, 621))
        self.output_text.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.output_text.setObjectName("output_text")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Метод Делфі"))
        self.groupBox.setTitle(_translate("MainWindow", "Налаштування даних"))
        self.execute_button.setText(_translate("MainWindow", "Здійснити оцінку"))
        self.label.setText(_translate("MainWindow", "Файл вхідних даних"))
        self.choose_input_button.setText(_translate("MainWindow", "..."))
        self.groupBox_3.setTitle(_translate("MainWindow", "Результати"))
